version: "3.9"

services:
  task-service:
    build:
      context: ./task-service
    container_name: task-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
      - redis
    env_file:
      - ./task-service/.env
    networks:
      - taskflow-net

  postgres:
    image: postgres:16
    container_name: taskflow-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
      POSTGRES_DB: taskflow
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - taskflow-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: taskflow-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - taskflow-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: taskflow-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - taskflow-net

  redis:
    image: redis:7
    container_name: taskflow-redis
    ports:
      - "6379:6379"
    networks:
      - taskflow-net

volumes:
  pg_data:

networks:
  taskflow-net:
    driver: bridge
